### ISSUE TITLE
Teensy Duino updated to v 1.56 for Arduino IDE 1.8.19

### ISSUE THREAD

**Issue by Defragster** [knickish/teensy_docker#2]
RE: "added support for teensyduino 1.54 and arduino 1.8.15"

PJRC updated TD 1.56 to support the IDE 1.8.19 that removed the JAVA vulnerabilities.

**Comment by knickish** [comment]
Thanks for letting me know. I'll probably just bring the repo private then, as my current employment contract doesn't allow me to work on open-source code.

**Comment by Defragster** [comment]
Interesting.  If you could leave it unchanged and open?  Not sure if somebody else might do a fork and fix?

It has utility - just may have some undone fixes.

**Comment by kiwiDaveENZED** [comment]
Hi knickish, with the contract situation would you be okay with me forking this repo? I am putting together an update to include  asm file (.S) compilation to cmake configuration, and would pull in Defragsters updates to versions as well.

**Comment by knickish** [comment]
Yeah that would be great. If I'm able to get the project approved or change jobs at some point would be happy to contribute to your fork or merge changes back in.

**Comment by Defragster** [comment]
@kiwiDaveENZED : feel free to run with it. I only brought the issue after I saw your post and it was the first I saw Docker.
I could make time to give it a test or a quick hand - but not looked into the mechanics of pulling the IDE and TD updates.

@knickish - good luck with staying employed and busy.

There is a new board in the tomorrow's mail, so I'll be looking after that between other tasks.

**Comment by kiwiDaveENZED** [comment]
Have a fork started at https://github.com/kiwiDaveENZED/teensy_docker 

Added assembly support and patched versions of teensy and arduino to latest. Unfortunately I am only testing on teensy so have to assume that the Arduino parts are still working (no reason to believe they wouldn't be though).

**Comment by knickish** [comment]
Sounds great, glad you found it useful.

**Comment by Defragster** [comment]
Nice work.

**Comment by knickish** [comment]
I've resolved my contractual issues and can now support this again. If you'd like to PR the updated work from your fork I'd be happy to merge

**Comment by knickish** [comment]
Actually, It looks like it was easy for me to grab the commits myself. Apologies, still not super used to github forks yet. I pulled in all your updated work on it, so this issue should be resolved now

**Comment by kiwiDaveENZED** [comment]
Coincidental! I picked this up again after months of not doing anything and saw your merge half an hour later! Glad you are able to do projects again - is nice to have something to chip away at.
